#!/usr/bin/env node
// forma doc — project an arc42 scaffold from c4-model.json.
// The DETERMINISTIC sections (context/building-block diagrams, container table, ADR index, stack)
// are filled from the model — so they can never drift from it. The JUDGMENT sections (goals,
// strategy, decisions, risks) are stubbed with TODO(forma) for a human/agent to write.
// Output: docs/architecture/ARCHITECTURE.scaffold.md (never overwrites a real ARCHITECTURE.md).
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { join, relative, isAbsolute } from 'node:path'
import { renderParts, renderBlock, replaceBetween } from './render.mjs'

const arg = (f, d) => { const i = process.argv.indexOf(f); return i > -1 ? process.argv[i + 1] : d }
const REPO = arg('--repo', process.cwd())
const MODEL = arg('--model', join(REPO, 'docs/architecture/c4-model.json'))
const OUT = arg('--out', join(REPO, 'docs/architecture/ARCHITECTURE.scaffold.md'))
if (!existsSync(MODEL)) { console.error('[forma doc] model missing: ' + MODEL + ' — run `forma gen` first.'); process.exit(1) }
const m = JSON.parse(readFileSync(MODEL, 'utf-8'))
// Deterministic, model-derived sections come from the shared side-effect-free renderer, so
// `forma doc` (writer) and `forma check` (attach freshness gate) render the block identically.
const { contextDiagram, containerTable, containerDiagram, adrs, stack, sys, containers } = renderParts(m, { repo: REPO })
const TODO = (s) => `> TODO(forma): ${s}`
const md = `<!-- forma: arc42 scaffold projected from c4-model.json. Deterministic sections are generated;
     do not edit them by hand — re-run \`forma doc\`. Fill the TODO(forma) prose, then promote to ARCHITECTURE.md. -->

# Architecture — ${sys ? sys.name : m.source.repo}

> **Format:** [arc42](https://arc42.org/) + [C4](https://c4model.com/). Generated by \`forma doc\` from
> \`c4-model.json\` (commit \`${(m.source.commit || '').slice(0, 8)}\`). The live explorer is \`c4-viewer.html\`.

## 1. Introduction and Goals
${TODO('one paragraph: what this system is and who uses it.')}
${TODO('top 3-5 quality goals as a table (goal → driver).')}

## 2. Architecture Constraints
Stack: **${stack}**.
${TODO('list hard constraints (language, deploy target, governance) with sources.')}

## 3. Context and Scope
${contextDiagram}
${TODO('in-scope / out-of-scope in one line each.')}

## 4. Solution Strategy
${TODO('the 3-5 load-bearing decisions and why (one table).')}

## 5. Building Block View
${containerTable}

${containerDiagram}
${TODO('for each container, a short drilldown paragraph (the explorer shows the leaves).')}

## 6. Runtime View
${TODO('1-3 key sequences (a request / a job / a sync) as mermaid sequenceDiagrams.')}

## 7. Deployment View
${existsSync(join(REPO, 'Dockerfile')) || existsSync(join(REPO, 'docker')) ? 'A Dockerfile/`docker/` was detected — document the deployment topology.' : TODO('how and where this runs (a mermaid flowchart).')}

## 8. Cross-cutting Concepts
${TODO('validation, security, persistence, error handling, i18n — where each lives.')}

## 9. Architecture Decisions
${adrs}

## 10. Quality Requirements
${TODO('measurable targets (coverage, latency, availability) + how each is verified.')}

## 11. Risks and Technical Debt
${TODO('known risks and debt, with links to any register.')}

## 12. Glossary
${TODO('domain and project terms.')}
`
// --attach <file>: inject the deterministic block between sentinel markers in an EXISTING doc
// (default: model.source.docPath), leaving human prose outside the markers untouched. `forma check`
// then governs that block. Default (no --attach) writes the standalone scaffold, exactly as before.
const attachIdx = process.argv.indexOf('--attach')
if (attachIdx > -1) {
  const next = process.argv[attachIdx + 1]
  let target = (next && !next.startsWith('--')) ? next : (m.source && m.source.docPath)
  if (!target) { console.error('[forma doc] --attach: no target (pass a file or set docPath in the model)'); process.exit(1) }
  target = isAbsolute(target) ? target : join(REPO, target)
  const prior = existsSync(target) ? readFileSync(target, 'utf-8') : ''
  let out
  try { out = replaceBetween(prior, renderBlock(m, { repo: REPO })) }
  catch { console.error('[forma doc] --attach: malformed forma markers in ' + relative(REPO, target) + ' — fix by hand'); process.exit(1) }
  mkdirSync(join(target, '..'), { recursive: true })
  writeFileSync(target, out)
  const rel = relative(REPO, target)
  console.log(`[forma doc] spliced generated block into ${rel} — ${containers.length} container(s); prose outside the markers untouched.`)
  // Register the target so `forma check` governs THIS file too, not just source.docPath — an
  // injected block nobody gates is exactly the false-green forma exists to kill. `gen` carries
  // the registry forward across regens.
  const known = m.source.attachedDocs || []
  if (rel !== m.source.docPath && !known.includes(rel)) {
    m.source.attachedDocs = [...known, rel].sort()
    writeFileSync(MODEL, JSON.stringify(m, null, 2) + '\n')
    console.log(`[forma doc] registered ${rel} in ${relative(REPO, MODEL)} — \`forma check\` now governs its block.`)
    console.log('[forma doc] commit the model: the registry lives in it, and a lost model un-governs the doc.')
  }
  process.exit(0)
}
writeFileSync(OUT, md)
console.log(`[forma doc] wrote ${relative(REPO, OUT)} — ${containers.length} container(s), context + container diagrams from the model.`)
console.log('[forma doc] deterministic sections filled; write the TODO(forma) prose, then promote to ARCHITECTURE.md.')
