#!/usr/bin/env node
// forma doc — project an arc42 scaffold from c4-model.json.
// The DETERMINISTIC sections (context/building-block diagrams, container table, ADR index, stack)
// are filled from the model — so they can never drift from it. The JUDGMENT sections (goals,
// strategy, decisions, risks) are stubbed with TODO(forma) for a human/agent to write.
// Output: docs/architecture/ARCHITECTURE.scaffold.md (never overwrites a real ARCHITECTURE.md).
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs'
import { join, relative } from 'node:path'

const arg = (f, d) => { const i = process.argv.indexOf(f); return i > -1 ? process.argv[i + 1] : d }
const REPO = arg('--repo', process.cwd())
const MODEL = arg('--model', join(REPO, 'docs/architecture/c4-model.json'))
const OUT = arg('--out', join(REPO, 'docs/architecture/ARCHITECTURE.scaffold.md'))
if (!existsSync(MODEL)) { console.error('[forma doc] model missing: ' + MODEL + ' — run `forma gen` first.'); process.exit(1) }
const m = JSON.parse(readFileSync(MODEL, 'utf-8'))
const byId = new Map(m.nodes.map((n) => [n.id, n]))
const sid = (s) => String(s).replace(/[^A-Za-z0-9_]/g, '_')
const name = (id) => (byId.get(id) || { name: id }).name
const C4 = { person: 'Person', system: 'System', external: 'System_Ext', container: 'Container', component: 'Component', store: 'ContainerDb', boundary: 'Container_Boundary', leaf: 'Component' }
const q = (s) => String(s == null ? '' : s).replace(/"/g, '')
const el = (n) => `${C4[n.kind] || 'Container'}(${sid(n.id)}, "${q(n.name)}"${n.tech ? `, "${q(n.tech)}"` : ''})`
const rels = (ids) => m.edges.filter((e) => ids.has(e.from) && ids.has(e.to)).map((e) => `  Rel(${sid(e.from)}, ${sid(e.to)}, "${(e.label || '').replace(/"/g, '')}")`).join('\n')

// context = nodes with no parent
const ctx = m.nodes.filter((n) => !n.parent)
const ctxIds = new Set(ctx.map((n) => n.id))
const contextDiagram = `\`\`\`mermaid\nC4Context\n  title System Context\n${ctx.map((n) => '  ' + el(n)).join('\n')}\n${rels(ctxIds)}\n\`\`\``

// containers = children of the system node
const sys = ctx.find((n) => n.kind === 'system') || ctx[0]
const containers = m.nodes.filter((n) => n.parent === (sys && sys.id))
const contIds = new Set(containers.map((n) => n.id))
const containerDiagram = containers.length ? `\`\`\`mermaid\nC4Container\n  title Container view — ${sys.name}\n${containers.map((n) => '  ' + el(n)).join('\n')}\n${rels(contIds)}\n\`\`\`` : '_No containers in the model yet._'
const leafCount = (id) => m.nodes.filter((n) => n.parent === id && n.kind === 'leaf').length
const containerTable = containers.length
  ? ['| Container | Tech | Leaves | What it does |', '|---|---|---|---|', ...containers.map((n) => `| ${n.name} | ${n.tech || '—'} | ${leafCount(n.id)} | ${(n.func || n.description || 'TODO(forma): describe').replace(/\n/g, ' ')} |`)].join('\n')
  : '_No containers yet._'

// ADR index if present
const adrDir = join(REPO, 'docs/adr')
let adrs = '_No `docs/adr/` found — record decisions as ADRs._'
if (existsSync(adrDir)) {
  const files = readdirSync(adrDir).filter((f) => /\.md$/.test(f) && !/readme|template/i.test(f)).sort()
  if (files.length) adrs = files.map((f) => { const t = (readFileSync(join(adrDir, f), 'utf-8').match(/^#\s+(.+)/m) || [, f])[1]; return `- [${t}](../adr/${f})`; }).join('\n')
}

const stack = (m.meta && m.meta.stack) || (sys && sys.tech) || 'TODO'
const TODO = (s) => `> TODO(forma): ${s}`
const md = `<!-- forma: arc42 scaffold projected from c4-model.json. Deterministic sections are generated;
     do not edit them by hand — re-run \`forma doc\`. Fill the TODO(forma) prose, then promote to ARCHITECTURE.md. -->

# Architecture — ${sys ? sys.name : m.source.repo}

> **Format:** [arc42](https://arc42.org/) + [C4](https://c4model.com/). Generated by \`forma doc\` from
> \`c4-model.json\` (commit \`${(m.source.commit || '').slice(0, 8)}\`). The live explorer is \`c4-viewer.html\`.

## 1. Introduction and Goals
${TODO('one paragraph: what this system is and who uses it.')}
${TODO('top 3-5 quality goals as a table (goal → driver).')}

## 2. Architecture Constraints
Stack: **${stack}**.
${TODO('list hard constraints (language, deploy target, governance) with sources.')}

## 3. Context and Scope
${contextDiagram}
${TODO('in-scope / out-of-scope in one line each.')}

## 4. Solution Strategy
${TODO('the 3-5 load-bearing decisions and why (one table).')}

## 5. Building Block View
${containerTable}

${containerDiagram}
${TODO('for each container, a short drilldown paragraph (the explorer shows the leaves).')}

## 6. Runtime View
${TODO('1-3 key sequences (a request / a job / a sync) as mermaid sequenceDiagrams.')}

## 7. Deployment View
${existsSync(join(REPO, 'Dockerfile')) || existsSync(join(REPO, 'docker')) ? 'A Dockerfile/`docker/` was detected — document the deployment topology.' : TODO('how and where this runs (a mermaid flowchart).')}

## 8. Cross-cutting Concepts
${TODO('validation, security, persistence, error handling, i18n — where each lives.')}

## 9. Architecture Decisions
${adrs}

## 10. Quality Requirements
${TODO('measurable targets (coverage, latency, availability) + how each is verified.')}

## 11. Risks and Technical Debt
${TODO('known risks and debt, with links to any register.')}

## 12. Glossary
${TODO('domain and project terms.')}
`
writeFileSync(OUT, md)
console.log(`[forma doc] wrote ${relative(REPO, OUT)} — ${containers.length} container(s), context + container diagrams from the model.`)
console.log('[forma doc] deterministic sections filled; write the TODO(forma) prose, then promote to ARCHITECTURE.md.')
